Repository cau-likelion-org/kiwi-client, pull requests merged in 2024-01, with the labels that each got.

#86 [FEAT] 문서역사 파싱 수정
  src/components/docHistory/DocHistory.tsx
Labels: FEAT

#110 [DESIGN] 검색화면 반응형 디자인 추가 적용 및 디테일 수정
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/search/SearchBodySection.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchFound.tsx
  src/components/search/SearchHeadSection.tsx
  src/components/search/SearchNotFound.tsx
  src/hooks/useSearchForm.ts
  yarn.lock
Labels: FIX, DESIGN

#111 [BUILD] push develop to main
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/search/SearchBodySection.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchFound.tsx
  src/components/search/SearchHeadSection.tsx
  src/components/search/SearchNotFound.tsx
  src/hooks/useSearchForm.ts
  yarn.lock
Labels: CHORE

#113 [REFACTOR] react-query 도입하여 서버 상태 관리 (search)
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/docs.ts
  src/app/ReactQueryProvider.tsx
  src/app/layout.tsx
  src/components/search/AutoCompleteBox.tsx
  src/components/search/AutoCompleteContainer.tsx
  src/components/search/SearchBodySection.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchFound.tsx
  src/components/search/SearchHeaderForm.tsx
  src/components/search/SearchNotFound.tsx
  src/components/search/SearchPageForm.tsx
  src/components/search/SearchResult.tsx
  src/hooks/useDebounce.ts
  src/hooks/useSearchAutoCompleteQuery.ts
  src/hooks/useSearchForm.ts
  src/hooks/useSearchQuery.ts
  src/types/request.d.ts
  src/types/search.d.ts
  yarn.lock
Labels: FEAT, REFACTOR

#114 [BUILD] push develop to main
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/docs.ts
  src/app/ReactQueryProvider.tsx
  src/app/layout.tsx
  src/components/search/AutoCompleteBox.tsx
  src/components/search/AutoCompleteContainer.tsx
  src/components/search/SearchBodySection.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchFound.tsx
  src/components/search/SearchHeaderForm.tsx
  src/components/search/SearchNotFound.tsx
  src/components/search/SearchPageForm.tsx
  src/components/search/SearchResult.tsx
  src/hooks/useDebounce.ts
  src/hooks/useSearchAutoCompleteQuery.ts
  src/hooks/useSearchForm.ts
  src/hooks/useSearchQuery.ts
  src/types/request.d.ts
  src/types/search.d.ts
  yarn.lock
Labels: CHORE
